services:
  db:
    image: postgres:16
    container_name: alemandan-postgres
    environment:
      POSTGRES_DB: alemandan
      POSTGRES_USER: alemandan
      POSTGRES_PASSWORD: alemandan
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U alemandan -d alemandan"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: