name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]
  workflow_dispatch: {}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      - name: Build with Maven (runs Testcontainers)
        run: mvn -B -V -Dstyle.color=always clean verify